// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjectMVC.Models;

public partial class Contacts
{
    [Key]
    [DisplayName("學院(所)或公司")]
    public string Id { get; set; }

    [StringLength(50)]
    [DisplayName("姓名")]
    public string Name { get; set; }

    [StringLength(255)]
    [DisplayName("信箱")]
    [EmailAddress(ErrorMessage = "E-Mail格式有誤")]
    [Required(ErrorMessage = "E-Mail為必填欄位")]
    public string Email { get; set; }

    [DisplayName("想留下的訊息")]
    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubmitDate { get; set; }
}