// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;

namespace ProjectMVC.Models;

public partial class Projects
{
    [Key]
    [DisplayName("編號")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [DisplayName("主題")]
    public string Title { get; set; }

    [DisplayName("內容")]
    public string Description { get; set; }

    [StringLength(255)]
    [DisplayName("圖片")]
    public string ImageUrl { get; set; }

    [Required]
    [StringLength(255)]
    [DisplayName("技術")]
    public string Technical { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateDate { get; set; }
}